/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ng2-keycloak.module';
import * as i2 from '@angular/http';
import * as i3 from './services/keycloak.core.service';
import * as i4 from './services/keycloak.auth.service';
import * as i5 from './services/keycloak.http.service';
export const Ng2KeycloakModuleNgFactory:i0.NgModuleFactory<i1.Ng2KeycloakModule> = i0.ɵcmf(i1.Ng2KeycloakModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.BrowserXhr,i2.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i2.ResponseOptions,
          i2.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i2.XSRFStrategy,i2.ɵb,
          ([] as any[])),i0.ɵmpd(4608,i2.XHRBackend,i2.XHRBackend,[i2.BrowserXhr,i2.ResponseOptions,
          i2.XSRFStrategy]),i0.ɵmpd(4608,i2.RequestOptions,i2.BaseRequestOptions,([] as any[])),
          i0.ɵmpd(4608,i3.Keycloak,i3.Keycloak,([] as any[])),i0.ɵmpd(4608,i4.KeycloakAuthorization,
              i4.KeycloakAuthorization,[i3.Keycloak]),i0.ɵmpd(5120,i2.Http,i1.keycloakHttpFactory,
              [i2.XHRBackend,i2.RequestOptions,i3.Keycloak,i4.KeycloakAuthorization]),
          i0.ɵmpd(4608,i5.KeycloakHttp,i5.KeycloakHttp,[i2.ConnectionBackend,i2.RequestOptions,
              i3.Keycloak,i4.KeycloakAuthorization]),i0.ɵmpd(512,i2.HttpModule,i2.HttpModule,
              ([] as any[])),i0.ɵmpd(512,i1.Ng2KeycloakModule,i1.Ng2KeycloakModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvZXN0ZXZhbi93b3Jrc3BhY2Uva2V5Y2xvYWstcXVpY2tzdGFydHMvZGF0YS1zZXJ2aWNlL3NyYy9uZzIta2V5Y2xvYWsubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2VzdGV2YW4vd29ya3NwYWNlL2tleWNsb2FrLXF1aWNrc3RhcnRzL2RhdGEtc2VydmljZS9zcmMvbmcyLWtleWNsb2FrLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
